# more5.rb

Why does the following code...

  def execute(block)
    block.call
  end

  execute { puts "Hello from inside the execute method!" }

Give us the following error when we run it?

  block.rb1:in `execute': wrong number of arguments (0 for 1) (ArgumentError)
  from test.rb:5:in `<main>'

---------

My answer:  it's a syntax error, i.e. execute(block) instead of execute(&block);
           It's expecting an argument (block) and isn't getting one